Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21487822_HW3.Models;

namespace u21487822_HW3.Controllers
{
    public class ImageController : Controller
    {
        // GET: Images
        public ActionResult Images()
        {
            List<FileModel> fileUploads = new List<FileModel>();
            //Fetch all files in the Folder (Directory).
            foreach (string newFile in Directory.GetFiles(Server.MapPath("~/Media/Image")))
            {
                FileInfo fileUp = new FileInfo(newFile);
                FileModel item = new FileModel();
                item.FileName = fileUp.Name;

                fileUploads.Add(item);
            }
            //Copy File names to Model collection.
            //The return below returns to the list here.

            //List<FileModel> ObjFiles = new List<FileModel>();
            return View(fileUploads);
        }
        public FileResult Download(string fileName)
        {
            //Build the File Path.                           /Media/Image/Something.jpeg
            string path = Path.Combine(Server.MapPath("~/Media/Image"), fileName);
            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            //Send the File to Download.
            //The OCTET-STREAM format is used for file attachments on the Web with an
            //unknown file type. These .octet-stream files are arbitrary binary data
            //files that may be in any multimedia format.
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        public ActionResult Delete(string fileName)
        {
            // Delete the file inside ~/Media/Document folder 
            string path = Path.Combine(Server.MapPath("~/Media/Image"), fileName);
            FileInfo file = new FileInfo(path);

            System.IO.File.Delete(fileName);
            file.Delete();
            //return RedirectToAction("Document()");
            return RedirectToAction("Images");
        }
    }
}

Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21487822_HW3.Models;

namespace u21487822_HW3.Controllers
{
    public class VideoController : Controller
    {
        // GET: Videos
        public ActionResult Videos()
        {

            List<FileModel> fileUploads = new List<FileModel>();
            //Fetch all files in the Folder (Directory).
            foreach (string newFile in Directory.GetFiles(Server.MapPath("~/Media/Video")))
            {
                FileInfo fileUp = new FileInfo(newFile);
                FileModel item = new FileModel();
                item.FileName = fileUp.Name;

                fileUploads.Add(item);
            }
            //Copy File names to Model collection.
            //The return below returns to the list here.

            //List<FileModel> ObjFiles = new List<FileModel>();
            return View(fileUploads);


        }
        public FileResult Download(string fileName)
        {
            //Build the File Path.                     /Media/Video/Something.mp4
            string path = Path.Combine(Server.MapPath("~/Media/Video"), fileName);
            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            //Send the File to Download.
            //The OCTET-STREAM format is used for file attachments on the Web with an
            //unknown file type. These .octet-stream files are arbitrary binary data
            //files that may be in any multimedia format.
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        public ActionResult Delete(string fileName)
        {
            // Delete the file inside ~/Media/Document folder 
            string path = Path.Combine(Server.MapPath("~/Media/Video"), fileName);
            FileInfo file = new FileInfo(path);

            System.IO.File.Delete(fileName);
            file.Delete();
            //return RedirectToAction("Document()");
            return RedirectToAction("Videos");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Document", "Document", "Document")</li>
                    <li> @Html.ActionLink("Images", "Images", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Videos", "Video")</li>
                    <li>@Html.ActionLink("About Me", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - INF272 HOMEWORK ASSIGNMENT 3</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>